name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Print env
        run: |
          node -v
          npm -v
          ls -la
          cat package.json

      - name: Install deps (npm)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Ensure Next present (safety net)
        run: |
          npx --yes next --version || npm i -D next@latest

      - name: Build (Next static export)
        run: npm run build

      - name: Verify static export exists
        run: |
          if [ ! -f out/index.html ]; then
            echo "❌ No out/index.html."
            echo "Make sure next.config.mjs includes:"
            echo "export default { output:'export', trailingSlash:true, images:{unoptimized:true} }"
            exit 1
          fi
          echo "✅ out/index.html found."
          ls -la out | head -n 50

      - name: Prepare artifact for Pages
        run: |
          touch out/.nojekyll
          if [ -f CNAME ]; then
            cp CNAME out/
          else
            echo "aayushmalla.com.np" > out/CNAME
          fi

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
